version: '3.7'
services:
    reverse-proxy:
        image: traefik:v2.2.0
        networks:
            - skynet
            - galaxy
        command:
            - "--metrics=true"
            - "--metrics.prometheus=true"
            - "--metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000"
            - "--metrics.prometheus.entryPoint=metrics"
            - "--metrics.prometheus.addEntryPointsLabels=true"
            - "--metrics.prometheus.addServicesLabels=true"

            - "--api=true"
            - "--api.dashboard=true"

            - "--log.level=INFO"

            - "--providers.docker=true"
            - "--providers.docker.swarmmode=true"
            - "--providers.docker.exposedbydefault=false"

            - "--entrypoints.web.address=:80"
            - "--entrypoints.websecure.address=:443"
            #- "--entrypoints.rabbitmq.address=:5672"
            - "--entryPoints.metrics.address=:8082"

            - "--certificatesResolvers.sec.acme.email=marcel.benders@icloud.com"
            - "--certificatesResolvers.sec.acme.storage=/letsencrypt/acme.json"
            - "--certificatesResolvers.sec.acme.httpChallenge.entryPoint=web"

        deploy:
            labels:
                - "traefik.enable=true"
                - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
                - "traefik.http.routers.api.rule=Host(`qaybe.de`)"

                - "traefik.http.routers.api.service=api@internal"
                - "traefik.http.routers.api.middlewares=myauth"
                - "traefik.http.services.api.loadbalancer.server.port=8080"
                - "traefik.http.routers.api.tls.certresolver=sec"
                - "traefik.http.middlewares.myauth.basicauth.users=marcel:$$apr1$$DIYU.5eS$$Uxui0JqCOge6OEr8xPjyl1"
            placement:
                constraints: [node.role == manager]
        ports:
            - "80:80"
            - "443:443"
            - "8082:8082"
            - "5672:5672"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik/letsencrypt:/letsencrypt

              #adminer:
              #image: adminer
              #deploy:
              #labels:
              #- "traefik.enable=true"
              #- "traefik.http.routers.adminer.entrypoints=websecure"
              #- "traefik.http.services.adminer.loadbalancer.server.port=8080"
              #- "traefik.http.routers.adminer.rule=Host(`adm.qaybe.de`)"
              #- "traefik.http.routers.adminer.tls.certresolver=sec"
              #restart_policy:
              #condition: on-failure
              #networks:
              #- skynet

              #whoami:
              #image: containous/whoami
              #networks:
              #- skynet
              #deploy:
              #labels:
              #- traefik.frontend.rule=Host:whoami.qaybe.de
              #- traefik.backend=whoami
              #- traefik.port=80
              #- traefik.frontend.auth.basic=marcel:$$apr1$$86cKZbLp$$fD4L00zFWf8fSpGdgBOEv.
networks:
    skynet:
        external: true
    galaxy:
        external: true
